version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      npm:
        patterns:
          - '*'
      security:
        applies-to: security-updates
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
      security:
        applies-to: security-updates
        patterns:
          - '*'
